[licenses]
allow = [
  # permissive licenses
  "Apache-2.0",
  "BSL-1.0",
  "ISC",
  "MIT",
  "Unicode-3.0",
  "Unlicense",
  "Zlib",
  # permissive license with unclear patent grant
  "CC0-1.0",
]

# Clearify licence: https://github.com/briansmith/ring/issues/902
# Plan to remove OpenSSL: https://github.com/briansmith/ring/issues/1827
[[licenses.clarify]]
expression = "ISC AND MIT AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]
name = "ring"

[advisories]
ignore = [
  # https://rustsec.org/advisories/RUSTSEC-2024-0436 paste! is unmaintained
  "RUSTSEC-2024-0436",
]

[bans]
multiple-versions = "allow"
